apiVersion: apps/v1
kind: Deployment
metadata:
  name: meenaxi-medicure-deploy
  labels:
    app: meenaxi-medicure-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meenaxi-medicure-app
  template:
    metadata:
      labels:
        app: meenaxi-medicure-app
    spec:
      containers:
      - name: meenaxi-medicure-container
        image: meenaxim/medicure
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: meenaxi-medicure-np-service
  labels:
    app: meenaxi-medicure-app
spec:
  selector:
    app: meenaxi-medicure-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31020
    port: 8080
    targetPort: 8080
